version: "3.8"
services:

  # Applications

  # catalog-service:
  #   depends_on:
  #     - ecomm-postgres
  #   image: "catalog-service"
  #   container_name: "catalog-service"
  #   ports:
  #     - 9001:9001
  #     - 8001:8001
  #   environment:
  #     # Buildpacks environment variable to configure the number of threads in memory calculation
  #     - BPL_JVM_THREAD_COUNT=50
  #     # Buildpacks environment variable to enable debug through a socket on port 8001
  #     - BPL_DEBUG_ENABLED=true
  #     - BPL_DEBUG_PORT=8001
  #     - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://ecomm-postgres:5432/ecommdb_catalog
  #     - SPRING_PROFILES_ACTIVE=testdata
  
  # order-service:
  #   depends_on:
  #     - ecomm-postgres
  #     - ecomm-rabbitmq
  #   image: "order-service"
  #   container_name: "order-service"
  #   ports:
  #     - 9002:9002
  #     - 8002:8002
  #   environment:
  #     # Buildpacks environment variable to enable debug through a socket on port 8002
  #     - BPL_DEBUG_ENABLED=true
  #     - BPL_DEBUG_PORT=8002
  #     - ecomm_CATALOG_SERVICE_URI=http://catalog-service:9001
  #     - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
  #     - SPRING_R2DBC_URL=r2dbc:postgresql://ecomm-postgres:5432/ecommdb_order
  #     - SPRING_FLYWAY_URL=jdbc:postgresql://ecomm-postgres:5432/ecommdb_order
  #     - SPRING_RABBITMQ_HOST=ecomm-rabbitmq
  
  # dispatcher-service:
  #   depends_on:
  #     - ecomm-rabbitmq
  #   image: "dispatcher-service"
  #   container_name: dispatcher-service
  #   ports:
  #     - 9003:9003
  #     - 8003:8003
  #   environment:
  #     # Buildpacks environment variable to enable debug through a socket on port 8002
  #     - BPL_DEBUG_ENABLED=true
  #     - BPL_DEBUG_PORT=8003
  #     - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
  #     - SPRING_RABBITMQ_HOST=ecomm-rabbitmq

  # edge-service:
  #   depends_on:
  #     - ecomm-redis
  #   image: "edge-service"
  #   container_name: "edge-service"
  #   ports:
  #     - 9000:9000
  #     - 8000:8000
  #   environment:
  #     # Buildpacks environment variable to enable debug through a socket on port 8000
  #     - BPL_DEBUG_ENABLED=true
  #     - BPL_DEBUG_PORT=8000
  #     - CATALOG_SERVICE_URL=http://catalog-service:9001
  #     - ORDER_SERVICE_URL=http://order-service:9002
  #     - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
  #     - SPRING_REDIS_HOST=ecomm-redis
  
  # config-service:
  #   image: "config-service"
  #   container_name: "config-service"
  #   ports:
  #     - 8888:8888
  #     - 9888:9888
  #   environment:
  #     # Buildpacks environment variable to configure the number of threads in memory calculation
  #     - BPL_JVM_THREAD_COUNT=50
  #     # Buildpacks environment variable to enable debug through a socket on port 9888
  #     - BPL_DEBUG_ENABLED=true
  #     - BPL_DEBUG_PORT=9888
  
  # Backing Services

  ecomm-postgres:
    image: "postgres:14.4"
    container_name: "ecomm-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  ecomm-redis:
    image: "redis:7.0"
    container_name: "ecomm-redis"
    ports:
      - 6379:6379
  
  ecomm-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: ecomm-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
